### PR TITLE
Fix infinite loop when specifying name of abstract base class as discriminator

### LINKED ISSUE #82: Infinite loop when specifying name of abstract base class as discriminator
### Source/destination types

```csharp
[JsonConverter(typeof(JsonSubTypes.JsonSubtypes), "Discriminator")]
abstract class Base {
	
}

class Derived : Base {
	public string Discriminator => "Derived";
}
```

### Steps to reproduce

```csharp
JsonConvert.DeserializeObject<Base>("{\"Discriminator\":\"Base\"}")
```

### Expected behavior

JsonSubTypes should throw a `JsonSerializationException`.

### Actual behavior

JsonSubTypes goes into an infinite loop and hangs.

### PR DESCRIPTION
**Pull request by kimsey0**
Also adds test for this condition. Fixes #82

### CODE REVIEW

File: JsonSubTypes/JsonSubtypes.cs [hunk 1]
```diff
@@ -241,11 +241,16 @@ private Type GetType(JObject jObject, Type parentType, JsonSerializer serializer
             Type targetType = parentType;
             JsonSubtypes lastTypeResolver = null;
             JsonSubtypes currentTypeResolver = this;
+            HashSet<Type> visitedTypes = new HashSet<Type> {targetType};
 
             var jsonConverterCollection = serializer.Converters.OfType<JsonSubtypesConverter>().ToList();
             while (currentTypeResolver != null && currentTypeResolver != lastTypeResolver)
```
Comment (manuc66) [inline JsonSubTypes/JsonSubtypes.cs]: Why not simply add the condition ` && jsonConverterCollection.Count > 0` ?

File: JsonSubTypes/JsonSubtypes.cs [hunk 2]
```diff
@@ -241,11 +241,16 @@ private Type GetType(JObject jObject, Type parentType, JsonSerializer serializer
...
             {
                 targetType = currentTypeResolver.GetType(jObject, targetType);
+                if (!visitedTypes.Add(targetType))
```
Comment (manuc66) [inline JsonSubTypes/JsonSubtypes.cs]: If you exit the loop a `JsonSerializationException` exception with the folowing message will be thrown :
`Could not create an instance of type JsonSubTypes.Tests.AbstractBaseClassDiscriminatorTests+MainClass. Type is an interface or abstract class and cannot be instantiated. Path 'Discriminator', line 1, position 17.`

I prefer the later

File: JsonSubTypes.Tests/AbstractBaseClassDiscriminatorTests.cs [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+
+        public class SubTypeClass : MainClass
+        {
+            public string Discriminator => "SubTypeClass";
+        }
+
+        [Test]
+        [Timeout(2000)]
+        public void DeserializingWithAbstractBaseClassDiscriminatorThrows()
+        {
```
Comment (manuc66) [inline JsonSubTypes.Tests/AbstractBaseClassDiscriminatorTests.cs]: Thanks for providing non regression tests !

What about asserting the message too ?

```cs
            var exception = Assert.Throws<JsonSerializationException>(() => JsonConvert.DeserializeObject<MainClass>("{\"Discriminator\":\"MainClass\"}"));
            Assert.AreEqual("Could not create an instance of type JsonSubTypes.Tests.AbstractBaseClassDiscriminatorTests+MainClass. Type is an interface or abstract class and cannot be instantiated. Path 'Discriminator', line 1, position 17.", exception.Message);
```

**Comment by manuc66** [comment]
@kimsey0 Don't bother with the appveyor failing build (it's ok, it's just because appveyor does not decrypt secured credentials for PR)

File: JsonSubTypes/JsonSubtypes.cs (hunk 1 above)
Comment (kimsey0) [reply JsonSubTypes/JsonSubtypes.cs]: I didn't have a good enough understanding of the code and loop invariant here to recognize that as a potential solution. I just saw a problem with repeatedly resolving the same target type, and implemented the most straightforward solution I could see to that.

Just adding `&& jsonConverterCollection.Count > 0` to the loop condition seems to cause the `ConcurrentThreadTest` and `Test` tests in `BaseIsAnInterfaceTests`, the `Demo` test in `DemoCustomSubclassMappingTests`, and the `Demo` and `DemoDifferentCase` tests in `DemoKnownSubTypeWithProperty` to fail. However, then changing it to a do while loop fixes that.

Would you prefer that as a solution? I can commit it to my fork or you can commit it there yourself (I have allowed edits from maintainers).

File: JsonSubTypes/JsonSubtypes.cs (hunk 2 above)
Comment (kimsey0) [reply JsonSubTypes/JsonSubtypes.cs]: If we keep the implementation with a hash set of visited types, I'll change it to just break out of the loop.

File: JsonSubTypes.Tests/AbstractBaseClassDiscriminatorTests.cs (hunk 3 above)
Comment (kimsey0) [reply JsonSubTypes.Tests/AbstractBaseClassDiscriminatorTests.cs]: Let's do that in the same commit where we remove the code that throws a custom "circular reference" exception.

File: JsonSubTypes/JsonSubtypes.cs (hunk 1 above)
Comment (manuc66) [reply JsonSubTypes/JsonSubtypes.cs]: no, let's use the HashSet to keep track of visited types

Comment (manuc66) [reply JsonSubTypes/JsonSubtypes.cs]: I think this solution is a better one:
image

It ensures that there is a progression in the loop without using a set

The proposed check I made on `jsonConverterCollection` is not correct because there might left some `JsonSubtypesConverter` in the list that does not apply to this type hierarchy

Comment (kimsey0) [reply JsonSubTypes/JsonSubtypes.cs]: You can still mess that up with a circular reference in three or more classes:

``` cs
[JsonConverter(typeof(JsonSubtypes), "Discriminator")]
[JsonSubtypes.KnownSubType(typeof(B), "D")]
public abstract class A
{
}

[JsonConverter(typeof(JsonSubtypes), "Discriminator")]
[JsonSubtypes.KnownSubType(typeof(C), "D")]
public abstract class B
{
}

[JsonConverter(typeof(JsonSubtypes), "Discriminator")]
[JsonSubtypes.KnownSubType(typeof(A), "D")]
public abstract class C
{
}

JsonConvert.DeserializeObject<A>("{\"Discriminator\":\"D\"}");
```

You may say that you're pointing the gun at your own foot at that point, but could it happen inadvertently?

Comment (manuc66) [reply JsonSubTypes/JsonSubtypes.cs]: Let's keep the HashSet

Comment (kimsey0) [reply JsonSubTypes/JsonSubtypes.cs]: Would you like the above A-B-C circle as a test as well?

Comment (kimsey0) [reply JsonSubTypes/JsonSubtypes.cs]: I have pushed the A-B-C test as well.

**Comment by manuc66** [comment]
@kimsey0 thanks
